# Generated by Django 4.2.6 on 2023-10-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_tour_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
