# Generated by Django 4.2.6 on 2023-10-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_max_participants_tour_price_touravailability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='exclusions',
            new_name='excluded',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='inclusions',
            new_name='included',
        ),
    ]
