# Generated by Django 4.2.6 on 2023-10-18 18:22

from django.db import migrations, models
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_rename_exclusions_tour_excluded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tours.models.tour_image_upload_path),
        ),
    ]
