# Generated by Django 4.2.6 on 2023-10-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id_proof_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='id_proof_upload',
            field=models.FileField(default='default/id_proof.pdf', upload_to='id_proof_uploads/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id_proof_type',
            field=models.CharField(choices=[('aadhar_card', 'Aadhar Card'), ('citizenship', 'Citizenship'), ('passport', 'Passport')], max_length=50),
        ),
    ]
